const state = { balance: Number(localStorage.getItem('prizeDropBalance') || 5), catches: JSON.parse(localStorage.getItem('prizeDropCatches') || '[]'), pending: null };
const $ = (selector) => document.querySelector(selector);
const icons = { 'Cosmic Claw': ['◕ᴥ◕', 'Nebula Bear', 'RARE', 6], 'Candy Capsule': ['♥', 'Cherry Heart', 'COMMON', 3], 'Plush Planet': ['☻', 'Orbit Plush', 'EPIC', 10], 'Pixel Vault': ['◆', 'Pixel Gem', 'LEGENDARY', 18] };
function save(){ localStorage.setItem('prizeDropBalance', state.balance.toFixed(2)); localStorage.setItem('prizeDropCatches', JSON.stringify(state.catches)); }
function render(){ $('#balance').textContent = `$${state.balance.toFixed(2)}`; $('#navCount').textContent = state.catches.length; $('#collectionCount').textContent = `(${state.catches.length})`; const shelf = $('#collectionItems'); shelf.innerHTML = state.catches.length ? state.catches.map((item, index) => { const rarity = item.rarity || 'COMMON'; const value = item.value || 2; return `<div class="catch-item"><div class="catch-icon">${item.icon}</div><p>${item.name}</p><small class="rarity ${rarity.toLowerCase()}">${rarity}</small><button class="sell-btn" data-index="${index}">SELL +${value} CR</button></div>`; }).join('') : '<div class="empty-state">Your shelf is waiting.<br /><span>Play a machine to catch your first prize.</span></div>'; }
function openModal(game, cost){ state.pending = { game, cost }; $('#modalTitle').textContent = `${game} is ready`; $('#modalCopy').textContent = 'One play, one chance, one shiny new thing for your shelf.'; $('#modalCost').textContent = `$${cost.toFixed(2)}`; $('#modal').hidden = false; }
function closeModal(){ $('#modal').hidden = true; state.pending = null; }
document.querySelectorAll('.play-btn:not(.disabled)').forEach((button) => button.addEventListener('click', () => { const cost = Number(button.dataset.cost); if(state.balance < cost){ showToast('Top up your balance to keep playing.'); return; } openModal(button.dataset.game, cost); }));
$('#closeModal').addEventListener('click', closeModal); $('#modal').addEventListener('click', (event) => { if(event.target.id === 'modal') closeModal(); });
$('#confirmPlay').addEventListener('click', () => { if(!state.pending) return; const { game, cost } = state.pending; const activeButton = [...document.querySelectorAll('.play-btn')].find((button) => button.dataset.game === game); const scene = activeButton?.closest('.game-card')?.querySelector('.machine-scene, .mini-scene'); scene?.classList.add('dropping'); closeModal(); $('#confirmPlay').disabled = true; setTimeout(() => { state.balance -= cost; const [icon, name, rarity, value] = icons[game] || ['✦', 'Mystery Prize', 'COMMON', 2]; state.catches.unshift({ icon, name, rarity, value }); save(); render(); $('#confirmPlay').disabled = false; scene?.classList.remove('dropping'); showToast(`${name} caught! Added to your shelf.`); }, 1600); });
$('#collectionItems').addEventListener('click', (event) => { const button = event.target.closest('.sell-btn'); if(!button) return; const item = state.catches[Number(button.dataset.index)]; if(item.rarity === 'LEGENDARY' && !window.confirm(`Are you sure? Sell your LEGENDARY ${item.name} for ${item.value} credits?`)) return; state.catches.splice(Number(button.dataset.index), 1); state.balance += item.value; save(); render(); showToast(`${item.name} sold for ${item.value} credits.`); });
function showToast(message){ const toast = $('#toast'); toast.textContent = message; toast.classList.add('show'); setTimeout(() => toast.classList.remove('show'), 3000); }
render();
$('#topUp').addEventListener('click', () => { state.balance += 10; save(); render(); showToast('$10 added to your arcade balance.'); });
